### ISSUE TITLE
Gösterilen soruyu arrayden silme

### ISSUE THREAD

**Issue by oktayyoruk** [alicangunduz/tanismada-sohbet-tikanmasin#1]
Soru Üret click event'inin sonunda, sayi değişkenini sorular array'inden kaldıran bir kod eklerseniz bir oturum esnasında aynı soruyu 2. kez görme ihtimalleri ortadan kalkar.

sorular.splice(sayi, 1);

**Comment by alicangunduz** [comment]
Yaptım , fikriniz benim için çok değerliydi çok teşekkürler.
